//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSETimeStamp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Timestamp = new HashSet<Timestamp>();
        }
    
        public int EmpID { get; set; }
        public string EmpFName { get; set; }
        public string EmpLName { get; set; }
        public Nullable<int> EmpCardID { get; set; }
        public string EmpPass { get; set; }
        public Nullable<System.DateTime> EmpBirth { get; set; }
        public string EmpDepart { get; set; }
        public string EmpEmail { get; set; }
        public string EmpHNo { get; set; }
        public string EmpSoi { get; set; }
        public string EmpRoad { get; set; }
        public string EmpSubDis { get; set; }
        public string EmpDistrict { get; set; }
        public string EmpProvice { get; set; }
        public string EmpPost { get; set; }
        public string EmpCall { get; set; }
        public Nullable<int> PermisID { get; set; }
    
        public virtual Permission Permission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timestamp> Timestamp { get; set; }
    }
}
