//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSETimeStamp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Holiday
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Holiday1 { get; set; }
        public Nullable<System.DateTime> ThisDay { get; set; }
        public string other { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Depart { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
