//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectSETimeStamp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimestampType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TimestampType()
        {
            this.Timestamp = new HashSet<Timestamp>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public string TypeDetail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Timestamp> Timestamp { get; set; }
    }
}
